### ISSUE TITLE
Run RepoFS as a background process

### ISSUE THREAD

**Issue by VitSalis** [AUEB-BALab/RepoFS#10]
RepoFS is currently a running process meaning that if the user running the process logs out the repository is unmounted.

**Comment by dspinellis** [comment]
This can currently be solved with *nohup*(1) and the shell's `&`.  However, background operation should be the default if RepoFS is provided in a command such as *mount_repofs*.

**Comment by VitSalis** [comment]
I agree. Currently, if RepoFS is installed via `setup.py` it adds a command `repofs` to the shell, that's similar to running RepoFS manually.

I suggest we add a parameter to the `main` function, that differentiates between running as a command line tool and running manually as a python script (for development purposes).

**Comment by dspinellis** [comment]
I think you can just look at argv[0].  But daemon commands typically provide -d flag which negates the auto-backgrounding and enables further debugging message logging.

**Comment by VitSalis** [comment]
Enabled running in the background in 4d9f6c7580e0d354cd794047f25d06d19bf0998b

We can add support for debugging messages in another issue.
