### ISSUE TITLE
Simplify installation and deployment

### ISSUE THREAD

**Issue by dspinellis** [AUEB-BALab/RepoFS#13]
It seems that RepoFS's dependencies are a bit tricky to satisfy. Providing a Docker image might solve this problem.

**Comment by VitSalis** [comment]
I agree. I'm not sure about adding docker as a requirement for the user though. A simpler solution would be to add a shell installation script. Are there any drawbacks to this approach?

**Comment by dspinellis** [comment]
It might be trickier to make the script portable across diverse distributions; witness the pain I experienced to install RepoFS on my system.  The requirements I would specify for the script are the following.
* It should have only a few easily-satisfiable dependencies (make and a C compiler is OK; a specific version of Python, libgit, or PyGit are not).
* Its execution should be self-contained; it should not mess up already installed facilities
* Its execution should not require administrator privileges (but it should be possible to use it as an administrator)

**Comment by VitSalis** [comment]
The installation issues arise on Debian 8.10. Installing pygit2 and fusepy in Debian 9.3 and Ubuntu 16.04 can be easily done via `apt-get install python-pygit2 python-fuse`. Debian 8.10 doesn't have `python-pygit2` in its repository.

I suggest we create a Debian package that installs `python-pygit2` and `python-fuse`. For older versions of Debian we could add a section in the README that links to installing pygit2 manually.

**Comment by VitSalis** [comment]
Updated installation instructions in commit f94b2765b111c6c5901808a7168af67c831513a6

I'll close this issue and we can deal with the debian packaging in another issue.
