### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by dspinellis** [AUEB-BALab/RepoFS#6]
So that we can more easily accept pull requests.

**Comment by VitSalis** [comment]
I suggest we add [Travis CI](https://github.com/marketplace/travis-ci).

I think we only need a `travis.yml` file that runs `make test` inside the `src` directory.

**Comment by dspinellis** [comment]
Agreed.  `make test` will only run the unit tests.  Ideally, we'd want to ensure test coverage has not decreased and be able to run some end-to-end integration tests, i.e. that the program can actually present a Git repo as a directory.  Let's start with the simplest parts.

**Comment by VitSalis** [comment]
OK, can you enable Travis for this repo? I don't have sufficient rights.

**Comment by dspinellis** [comment]
I enabled [the project on Travis CI](https://travis-ci.org/AUEB-BALab/RepoFS).

**Comment by VitSalis** [comment]
Thanks! This issue depends on the solution of issue #13 since travis needs to first install repofs before running any tests.

**Comment by VitSalis** [comment]
Fixed on 2fdd10ad55ebecd517f68ecf4383542b1e6ff00b
